import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    profile: "Profile",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    chatColor: "Chat Color",
    appColor: "App Color",
    language: "Language",
    email: "Email",
    changeEmail: "Change Email",
    logout: "Logout",
    back: "Back",
    appearance: "Appearance",
    actions: "Actions",
    // Chat
    howCanIHelp: "How can I help you today?",
    askAnything: "Ask anything...",
    askMeAnything: "Ask me anything — I'm here to assist.",
    newChat: "New Chat",
    chat: "Chat",
    reminders: "Reminders",
    learning: "Learning",
    history: "History",
    // Reminders
    myReminders: "My Reminders",
    create: "Create",
    searchReminders: "Search reminders...",
    createReminder: "Create Reminder",
    editReminder: "Edit Reminder",
    title: "Title",
    description: "Description",
    date: "Date",
    time: "Time",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    noReminders: "No reminders yet",
    noMatch: "No reminders match your search",
    createFirst: "Create your first reminder",
    // Landing
    getStarted: "Start",
    features: "Features",
    aiAssistant: "AI Assistant for Everyday Life",
    heroTitle: "Your AI assistant for learning, chatting, and staying organized",
    heroDesc: "Finda brings the power of AI to your fingertips. Chat, learn, set reminders, and get things done smarter and faster.",
    noCreditCard: "No credit card required",
    everythingYouNeed: "Everything you need in one place",
    powerfulFeatures: "Powerful features to simplify your day-to-day life.",
    aiChat: "AI Chat",
    aiChatDesc: "Talk with AI naturally and get instant, context-aware support whenever you need it.",
    aiLearning: "AI Learning",
    aiLearningDesc: "Watch and learn with AI-powered content tailored to your pace and interests.",
    smartReminders: "Smart Reminders",
    smartRemindersDesc: "Organize your tasks and reminders effortlessly and never miss what matters.",
    howItWorks: "How it works",
    threeSteps: "Get started in just 3 simple steps.",
    signUp: "Sign up",
    signUpDesc: "Create your account in seconds.",
    chooseFeature: "Choose a feature",
    chooseFeatureDesc: "Pick what you need: chat, learn, or reminders.",
    startUsingAI: "Start using AI",
    startUsingAIDesc: "Let AI help you get things done smarter.",
    startToday: "Start using Finda today",
    startTodayDesc: "Your AI assistant for a smarter and more productive life.",
    startNow: "Start Now",
    // Auth
    createAccount: "Create account",
    joinFinda: "Join Finda and start your journey",
    fullName: "Full name",
    password: "Password",
    atLeast8: "At least 8 characters",
    includeNumber: "Include a number",
    includeUppercase: "Include an uppercase letter",
    orContinueWith: "or continue with",
    comingSoon: "Coming soon",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
    welcomeBack: "Welcome back",
    signInToAccount: "Sign in to your account",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    dontHaveAccount: "Don't have an account?",
    createOne: "Create one",
  },
  ar: {
    profile: "الملف الشخصي",
    theme: "المظهر",
    light: "فاتح",
    dark: "داكن",
    chatColor: "لون المحادثة",
    appColor: "لون التطبيق",
    language: "اللغة",
    email: "البريد الإلكتروني",
    changeEmail: "تغيير البريد",
    logout: "تسجيل الخروج",
    back: "رجوع",
    appearance: "المظهر",
    actions: "الإجراءات",
    howCanIHelp: "كيف يمكنني مساعدتك اليوم؟",
    askAnything: "اسأل أي شيء...",
    askMeAnything: "اسألني أي شيء — أنا هنا للمساعدة.",
    newChat: "محادثة جديدة",
    chat: "محادثة",
    reminders: "تذكيرات",
    learning: "تعلم",
    history: "السجل",
    myReminders: "تذكيراتي",
    create: "إنشاء",
    searchReminders: "البحث في التذكيرات...",
    createReminder: "إنشاء تذكير",
    editReminder: "تعديل تذكير",
    title: "العنوان",
    description: "الوصف",
    date: "التاريخ",
    time: "الوقت",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    noReminders: "لا توجد تذكيرات بعد",
    noMatch: "لا توجد نتائج مطابقة",
    createFirst: "أنشئ تذكيرك الأول",
    getStarted: "ابدأ",
    features: "المميزات",
    aiAssistant: "مساعد ذكي للحياة اليومية",
    heroTitle: "مساعدك الذكي للتعلم والمحادثة والتنظيم",
    heroDesc: "فيندا يضع قوة الذكاء الاصطناعي بين يديك. تحدث، تعلم، ونظم مهامك بذكاء.",
    noCreditCard: "لا حاجة لبطاقة ائتمان",
    everythingYouNeed: "كل ما تحتاجه في مكان واحد",
    powerfulFeatures: "ميزات قوية لتبسيط حياتك اليومية.",
    aiChat: "محادثة ذكية",
    aiChatDesc: "تحدث مع الذكاء الاصطناعي بشكل طبيعي واحصل على دعم فوري.",
    aiLearning: "تعلم ذكي",
    aiLearningDesc: "شاهد وتعلم محتوى مخصص لوتيرتك واهتماماتك.",
    smartReminders: "تذكيرات ذكية",
    smartRemindersDesc: "نظم مهامك وتذكيراتك بسهولة ولا تفوت شيئاً.",
    howItWorks: "كيف يعمل",
    threeSteps: "ابدأ في 3 خطوات بسيطة.",
    signUp: "سجل",
    signUpDesc: "أنشئ حسابك في ثوانٍ.",
    chooseFeature: "اختر ميزة",
    chooseFeatureDesc: "اختر ما تحتاجه: محادثة، تعلم، أو تذكيرات.",
    startUsingAI: "ابدأ باستخدام الذكاء",
    startUsingAIDesc: "دع الذكاء الاصطناعي يساعدك.",
    startToday: "ابدأ استخدام فيندا اليوم",
    startTodayDesc: "مساعدك الذكي لحياة أكثر إنتاجية.",
    startNow: "ابدأ الآن",
    createAccount: "إنشاء حساب",
    joinFinda: "انضم إلى فيندا وابدأ رحلتك",
    fullName: "الاسم الكامل",
    password: "كلمة المرور",
    atLeast8: "8 أحرف على الأقل",
    includeNumber: "يحتوي على رقم",
    includeUppercase: "يحتوي على حرف كبير",
    orContinueWith: "أو تابع باستخدام",
    comingSoon: "قريباً",
    alreadyHaveAccount: "لديك حساب؟",
    signIn: "تسجيل الدخول",
    welcomeBack: "مرحباً بعودتك",
    signInToAccount: "سجل دخول إلى حسابك",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت كلمة المرور؟",
    dontHaveAccount: "ليس لديك حساب؟",
    createOne: "أنشئ واحداً",
  },
  sv: {
    profile: "Profil",
    theme: "Tema",
    light: "Ljust",
    dark: "Mörkt",
    chatColor: "Chattfärg",
    appColor: "Appfärg",
    language: "Språk",
    email: "E-post",
    changeEmail: "Ändra e-post",
    logout: "Logga ut",
    back: "Tillbaka",
    appearance: "Utseende",
    actions: "Åtgärder",
    howCanIHelp: "Hur kan jag hjälpa dig idag?",
    askAnything: "Fråga vad som helst...",
    askMeAnything: "Fråga mig vad som helst — jag finns här för att hjälpa.",
    newChat: "Ny chatt",
    chat: "Chatt",
    reminders: "Påminnelser",
    learning: "Lärande",
    history: "Historik",
    myReminders: "Mina påminnelser",
    create: "Skapa",
    searchReminders: "Sök påminnelser...",
    createReminder: "Skapa påminnelse",
    editReminder: "Redigera påminnelse",
    title: "Titel",
    description: "Beskrivning",
    date: "Datum",
    time: "Tid",
    cancel: "Avbryt",
    save: "Spara",
    edit: "Redigera",
    delete: "Radera",
    noReminders: "Inga påminnelser än",
    noMatch: "Inga påminnelser matchar din sökning",
    createFirst: "Skapa din första påminnelse",
    getStarted: "Börja",
    features: "Funktioner",
    aiAssistant: "AI-assistent för vardagen",
    heroTitle: "Din AI-assistent för lärande, chatt och organisation",
    heroDesc: "Finda ger dig AI-kraft. Chatta, lär dig, sätt påminnelser och bli mer produktiv.",
    noCreditCard: "Inget kreditkort krävs",
    everythingYouNeed: "Allt du behöver på ett ställe",
    powerfulFeatures: "Kraftfulla funktioner för att förenkla din vardag.",
    aiChat: "AI-chatt",
    aiChatDesc: "Prata med AI naturligt och få omedelbar, kontextmedveten support.",
    aiLearning: "AI-lärande",
    aiLearningDesc: "Titta och lär med AI-drivet innehåll anpassat till din takt.",
    smartReminders: "Smarta påminnelser",
    smartRemindersDesc: "Organisera dina uppgifter och missa aldrig det som är viktigt.",
    howItWorks: "Så fungerar det",
    threeSteps: "Kom igång i bara 3 enkla steg.",
    signUp: "Registrera dig",
    signUpDesc: "Skapa ditt konto på sekunder.",
    chooseFeature: "Välj en funktion",
    chooseFeatureDesc: "Välj det du behöver: chatt, lärande eller påminnelser.",
    startUsingAI: "Börja använda AI",
    startUsingAIDesc: "Låt AI hjälpa dig att göra saker smartare.",
    startToday: "Börja använda Finda idag",
    startTodayDesc: "Din AI-assistent för ett smartare och mer produktivt liv.",
    startNow: "Börja nu",
    createAccount: "Skapa konto",
    joinFinda: "Gå med i Finda och starta din resa",
    fullName: "Fullständigt namn",
    password: "Lösenord",
    atLeast8: "Minst 8 tecken",
    includeNumber: "Innehåller en siffra",
    includeUppercase: "Innehåller en stor bokstav",
    orContinueWith: "eller fortsätt med",
    comingSoon: "Kommer snart",
    alreadyHaveAccount: "Har du redan ett konto?",
    signIn: "Logga in",
    welcomeBack: "Välkommen tillbaka",
    signInToAccount: "Logga in på ditt konto",
    rememberMe: "Kom ihåg mig",
    forgotPassword: "Glömt lösenord?",
    dontHaveAccount: "Har du inget konto?",
    createOne: "Skapa ett",
  },
};

const defaultPrefs = { theme: "light", chatColor: "#193B68", accentColor: "#193B68", language: "en" };

function loadPrefs() {
  try {
    const stored = localStorage.getItem("finda_prefs");
    return stored ? { ...defaultPrefs, ...JSON.parse(stored) } : defaultPrefs;
  } catch { return defaultPrefs; }
}

const AppContext = createContext();

export function AppProvider({ children }) {
  const [prefs, setPrefs] = useState(loadPrefs);

  useEffect(() => {
    localStorage.setItem("finda_prefs", JSON.stringify(prefs));
  }, [prefs]);

  const t = (key) => translations[prefs.language]?.[key] || translations.en[key] || key;
  const rtlLangs = ["ar", "he", "fa", "ur", "ps", "sd", "ku"];
  const isRTL = rtlLangs.includes(prefs.language);

  const updatePref = (key, value) => {
    setPrefs((prev) => ({ ...prev, [key]: value }));
  };

  return (
    <AppContext.Provider value={{ prefs, updatePref, t, isRTL }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
